language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: pachkun
  password:
    secure: OXLQDu+AiZM608BO2rhYhnbEIABfjpAxIHnHGhY/AQogguZk/OF5vlyJUONzx2seZMByxtaHOBKJu2DppdoC2ddpceHJe+QU8cQRE2JNE/bAa957hH+/Z3DLydDaU7AHAyBO9R74/IA1ZtREqiE5xEIGNeQZsmCeXgsILgZHSacyJh3SQGwWkCBtfBrUdMaae6QHLZGUJJWni6XvPClt0yQD9iJFPwwZg3yp9gdqExnuJwIo4A7Kq6Wi/jSffaCUOIFeCeIh65qYl9g2VyqjTCMl+7ynmKVPuz992XDLy+5YA9fQ4SfDllBThotY9hOVUaZoFFJaq6R+2nvaXZm9gmv6MqPh4M9aUMxYz3kepbyXIXTLvs66crqOvw3208ZZKtAqhzYjYRtQZgZ0ub9SryUxxH8D282Dgk3dcy45sfciJZAIukJnMh9Jw+ESYe6JmJo4vy2bqzg5MG8JIPrIsV6sd2g8aWh3l8hc/CupMJblaMCgim6YAmGFz7L/5Zqh/g00R3WFbE7MyIw8jbbrnaYOkvlQkhF8Rng+074O+YCsEapSRV6PygysbHJHUpZLwNgG2StPNGIcTXp4WAKN7oHCCH+7sJ30fzfz0l0yHvrzFhzURXnNae+PcxNIOs/RwETMgBD9POa4/8QJ8RCO3pwJF64PqmUBGiiFxIvFj/k=
  on:
    all_branches: true
