language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: pachkun
  password:
    secure: bAlApOn/4AzABS2eUFHny/ibX+SxpifuES0WAOkSoyPTgWO3sp9dp4NSH9IoF8oZhS0UAeKlQ6YVbifg3H7eGRI3lCseY7/FdG0maxAsy32wf9FXNYYv+Jzlv1CH7+b4F7w3rffe0t06kpa9SqN/6aFn8+X4LQPk7dRp/Nk37KDpEWjq03na/uxeQHTvF5JrNP5XU8qt0Vl/nJ4VOi4V+2bvXbqKuf+XKtzLK/Ufupe/gbsEp12YZvG2ZU8nIu1c+P33bHdefkIUTSGtaxApKqsueQDADoPcLtRO0FPax+TrIrAOvCYwV5b6jvbtI8vGtc3s5WlcwSKbXh3fxaywEvP0cU4H9ftvG6y6tYkaRTQNy0of35StMbrgIrwiTldNmlAmlq9RdwAibzJtcvRaGz4dO514HR+VeaP5/Ktn2APmvvAJl3xPBLvbrJXiMr8RmtJEhbKTP7qfYyicgFNp6U6pvL8JDJUypxtwT6lmmQ5h4TwtM6eOTDHBd4gfImwvOoaefvcztVaEOdKLxF8Br79a4ge0X+hWq1PUoatyBfGYPBcY4O+tor4I/PPVYFm/WVnaBSBvpENMBck9VDkqIWnbrW7m8bNJPfW4T+ABrZsyUBbfIIPTohvBdWAiEf2T5B2teKVwVaXqr959Watihn8P+wBMQG5T0AZ72QtXGoA=
  on:
    all_branches: true
