language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: pachkun
  password:
    secure: F+wMlHDrn9+1/wBf2P9do1h2u2WlVqZFKotO3w8I49mNVN7aojkPMVaowFKY9kZ6zfcIXgM+X0we32zF8MjOx+G7a8fFwkUP3Q2XmW3icpTPwKvHtFYgEC4gBGVjgJNPHIk5VH+SUtttDEYH1YtmzlLuzJJEOTs305P409MBHQ/mBDkewwTIrwSFyaQgqHwD2yF52wpFQ4t5NlqLG2NfsBmDS0e+a0YRUW8aC3ViAO/n0s9BqEK8qT8RS4Lz/UIoXgtBC6pqLwz/W4QNcoxbdn4VqF4ZtbMQF3RyXW9qLPlPi1yOLWXoHsf9YUAOx8GzLqkQEoQigqhqAZ9zb+FiL/ZEB9J04fzp53uhPNeGPTWUmVC1FAHw6WKnjfp8CSnUQgr4ffPnVwuxw2wJuy+JYIEK8ofyBmbGC9staX4VtDqygOPANueCB2BEwY4qO7OIe2XCffQtG4SB6fXlLGK6wqA1Bb5vB4q4cQKsgRYjyv/H29rzaq9o+GtBlt/N52E94I8RAcakcvOzm7H34zO9pegsxJ1an5MlTvolhKeQzYtHqg8rwGXvi+O3pH06a2traK387xstXxxMydmOEKfz84MTUz0LNHeuG5HNaZS7clYiONcC8RSF9jLeC/tEOulaXo725qLMzRxzxPAt9vU1ObSIMNbH35/pHSAXBlCdalw=
  on:
    all_branches: true
