language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: pachkun
  password:
    secure: Zd6dlqstsMo4nGT3mOg5gkdxCSCEJOPjsjKKlDtY98WGdAgNih+gBMuQZBwf2yI6ZR3uMSmt7eXc1gKkHct7HOfQN0tAzcLfDXB+DBQNCmpzPExPmBIVK8zBCKwLfPC/CA1abYu0HeA/x5WgHj+NlD+HpNk/elREbgNcjjdVKqvGwGYxy+G0+bxTbyJXTMex6+8NJFdJGImZdeWH8fpNM/QeQ0KfmKa64CzbKwoVs/hnwyJhuCqfYdQ3Ng+bKPiFhYFtFP5Z63s/8oTFXlQBVCEBjkTHTG/xhIbuNd7X6bfdgNFfnNR9AqGOUhfIwaeUeO6GVmiEnfdAV9vpIBXhRji/uxt0NzJZWzfhGZ6hcV4h4RA+yz4WNpvGU+NOrhNSnDS87NYSUsBCBKOxxUqCjCXTF/7UqzubG8QfzD6V2S0CP2mKE19hu1QfY4lmid/KwdV2eElyhJgs0VkJtqIWbgsnfc93UVYtAASDTi15mQ6w524b0bDN0a0G4EWgYNN7e3lQakf4IOdN07TOzqiJcUZtowE1xT6pNx8KOG0VkpuXfBh4egV8nX2qqSBZ9FOk6R7orLV7zHEpAb6WYWK9UYP19kdxT3+60/Agsg3ROIIZkAVE47ET0BVZi4nNpdcZXnYBXHZIjC1NnduXLl3HGo9ZlqvPO5PNW/sqKHwCXZc=
  on:
    all_branches: true
