language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: pachkun
  password:
    secure: J9OooNLQty92pGy2f03Cb7NAxZA2o8+YyWV83AogAlw3vOEyi4Lo4R1WN1Z5AAL3ud8ERcakuYivzGEP/6zA0q1ERXliQh5Gm77inHYy24MptoaWZjcdaEGZO9hUPt5kpe3bUsPcy2sIo1omSK/St286+Ejbemm2oEgCw4rmcS8AksDzuSV+GUsPds/z3SGUHT/UhDN5+l79LxoWJG3EOABPN5+U83G29oYYdr8JGo5JXYEkbeP62LA4ihF3DlC5+Ra2NKQEjuFlufK4wlPYEymPIgoI5+h8tQH2ajhgRDYbkGPwgtVal4xyy/x+F4rHznkpOL+SJc/8dXN96XpihLY+6uzfUXQJ8MLXUNPKoai0IBh+Ky7OdVu9HzKpRkAkE4xeXk5DPi8lkrBbESj7d71D4W7U53PDgVXtj+JffGDeAwyoLpHyPDTmfNRA0f4JstCM4x5KeLh7/dNhtCKOlOVxFIqTD14SDaXAKtvbeH0hFm+m5neWcrpWUNLrS07pIAOy5jGfLoVzek+PZdEAUdYLwAvgWrV9SkRpQ2rsukOW8EaXtF/wz0PppLOCQ8975rfW9L2/DDwcjiuS0tRvywI+oz2Lo6NzDawqOP6Dcy9HVJ+Zo0eeVwM+oAfgxA+6dhY3g3IbNwjJNTEGo8CWHPKq5e6JODmCqCTzZelCNXo=
  on:
    all_branches: true
