language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: pachkun
  password:
    secure: "f4+bRZRJ2RlHnvoQYt79PjJQ6pW22dDgsbA0wLeu4Sd7mIon+k4Wm/XS/yCBBYNEJ32iLKE5Gkf+SqBEMTgC6tmh89wB6aL3rMffpLV1LcJu2NkrtHtY8Ot0dckuVTtQnCom//tKWnR8o0S6J9+fx7TtY2IDLtQ8MKXrMXtlwIA8NH5JiBIeL50Zc7Y5kWlQY7dLmb0US7cNpI49U1vG7nooeoFVgmAyUuRGqodIPafL+I0gP8Pk3xELZl/f8J2c9I66v7nvKyrKvhkYo/54KUsfGoxKHAV2EoA0Mi84+jSrjpLa/qu09z7FnrM5JodmEtCAQyAjLEcyrYDCF9LQcp4z3vkD/dKSv5488zFNdmAlCogId+krYtg0kioAJ+bJMQ4OU1n+AxPOgirppgJtIQ1rafXVUgPUg7w2heBwEY1toaUDq285c4yim1R+KHqXio3t+xPSyExjodhu/NepGBuYdvZv6u56xHrJIj07JUhcxKSdoxxi9p1dy40Jx8+
9Orv18fzsuDKI6BiX5NEM0CGhvuCqKtg3u5Ji8bJw1KwdTvOomYIgoQeqXsaDJuSpwpuoAtwOIRfXOGaOQkyX4748E7oq9nB0TDDHoUwqofPO02lMo1P0XLHJ+nbdGnbThpx4RQP2L+5sbjkt1geoKTaM1ULD1HtoYXY5a7GqGq8="
  on:
    all_branches: true
