language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: "pachkun"
  password:
    secure: "ZQ1pGqGtZQ+TEbydY4l+H+iFkU9tlKff7X3HVjiacTKUaIwvL/wwGdMcAPqLBk+TnmVJRv1vslMFFj+t9IB6nlDiEy5NgwykdI5cmizr0hgy6OgXUTFcF3Z/SDNtZVlu/MlPAXW0ayBadmNFsvSjRNHXb0ddhQFY0Ly+40Sc3kXmNtXITtrj5MDLRElr9ArZupNDw3KW4a4HD4EF+liyjD6JRNUfj4Y9AEFPHFp+DOha4HiUGHEh6YledSM3YuUnZ1xzMfTbU+bsP7YLLZkEk2LwyeTYAtSWtC766XM6oD1Ih/y8kxwPgeNs9/tUWKH63waBk47/fkk5DbC5rJRqK9qa2jiIEad5gMaZrjC0jE0spsCbs7HeB/Tz0OXf3+mCMp6ZTyfe005HCvPxljeVTHeVkYes6GDYQDuAS8jyy9dTgx1rhH94aURDJNt6edrGGCsaLbianK9uOny32aMuk/5JF1BJw1HW9NeS15w+KAne3+yJKxcgBdzkA+eHxG5yECW54hf1H/5tS/H2uHIpj2FbZDdG3eyOvyWZPfdPJ38m3Bc1KyXFAvEWkk1VOMIlQiiDWz/95QN3B6zyEW0gprIgh5pvOJzRPEn1fY/iWq1Sb/rnhO+AVE7D9MGiK39ql8XqTCR44W0rzSVxtdS3oN1u8j+Fv4tBxhadxaKrN+4="
  on:
    all_branches: true
