language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: pachkun
  password:
    secure: My89+jfTGii1FJAXSMtE3kvUtRqd4EkuG6qMxrwip5X0fOTfh95RgVK+d6mO3P1IYlRkgijNJLEFVoYXdCCWjLr4rYNpJl0nboejJGF5vdngDq01dv9TwhRcliYfXGvbOLQ6fwzdAq8fU3JlWp7UIZ39FaMwC7ugFJ2l54vmgBWiYaJIJev3hqviUKwXvONJ7AP4uXt18VFZqd7mIzKetgvJnfOFHrYBdeYcOjoox13xmqzCDgmrEKjRRpeUUhez3cVZIke2iAySn0YjOfYA8sbpOVMVeWKdXcc2cPErdP0OQ2PwXwdiTnqO3GvZbXFIhcj9qoJDjlKTZUh4CzS6BCXGevikruFItZtsDRYhG2kwhoUSFaLCuQfGvG/p7JnfmGnnfFurYXkXYyPXxRgvp4bX2Xw3xrm8bF7f6UPVoZAx0LhYCQWEy3J7y9NMlcZ+YtOSBWlwfMGslwn9fkyvvrApFQruTTsvdq+nes7mVAu13rrRl1G3BaZkWnP9QRNHrH9Y83qf2HU72TCwv/TT/pg25eAE/7f0x6/fuomiWSVw7qAYs2CFskYuWIxoBCaF0y7+EEZrhI3pFxLnKbNA9RDOKO6FHUtcgfPJ2p6Zg0B9joS0Ixobwv6hdcVPSknIcWADjVmrGWyJLAT36oW/XJW3d17/zgzdyBJ8bKgkZrs=
  on:
    all_branches: true
