language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: pachkun
  password:
    secure: eu1lvbyCYt/SX1yIiyBsoDp2LQ/GLSGDWeAONko5S1jmzC990B1mUxAsWGcnKnG1gfxEEiSnznbGeAP9+xikeu2mQKNIxCvmdRKSHHVTHtRV1msZVFKN7gqjR0YW0oeIWL4YDl8G/tEH8sXSyvSObbg04aiyy46GFrHp5dXpkiCKgKSFXaNuLYK0pkEyU5T/pjtRNles5l2whtIBoUPbdyynibysqvSARndOIs+Q1dsUWeplwsih3OCHYrxpTw3s4FNBHoo4FqoBudNypj9wC09TZFUpUHEKdNQRuhe8KIfmsjiDc0StonS0Ii5s4UMyi7mZYXe8DjIL5jCXWmTC7lUeJoc8FHl2CxybVEUTQmMAI/2XLuzbdcvG1J2QPPAjOV7CjVOoS6yhGOujgA0lADXXFNw/3RPoDjhLmuvG1oSyJmYJQPCG14XFrkHV7X1FfaF4WfWz4NneE48Ob+JR44y4kW+hHxBzQlwf3Bhet1IdYyoOp+j2w1Bjt+OJDNpE7Uep6t8vA8hNJY0Lg/Lo8/DuPcDPmmPfHs54ErtAiGQYgg95okZpWqC4FQIGekpqqiSJNSG7G/GwtbWKZypFGsKuBkZ7iN4tSN9OowxTZJD9cLnD568OUp7P960/TNERFILcgDD9MpQIifTZMmM6MXqoIIzIdlF1SD35znsP1qg=
  on:
    all_branches: true
