language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: pachkun
  password:
    secure: MtY9PuSudBDmUYoT1MMRXJJ4ohV8H+C96647m5LQ2c1iWNOHXhKYU3gj7kpdU/AwerEHkIBXIvylaC8OwQfxsS2G/KZzeMCGh9Z2S7QN2J/NYFlh/enP5l7PBIdgNLbMf2ecnxF4WpjTJeOOrfz/E4aAR9EQWTZIUhNInkxvk22qHIreAHxKCTAUseNjH5iezkGgnbII3jgg9Pr0b3hyriJh/qxJVevmt8p+3iGMtlKAhSGbcsRannF6DO3PEDLbMLKkquiwLBVEr7hD+P6UjoGnrgiCFktEpjXrUgDsYWJ1jLGLv4E06auobi3+iChz8S6HHLt2Rm/QrjbUR34LDHWRM/uJRa+Deg81+HBCHcSpVRj8IqZioK25eleUd2bWMR1t6L0sI1RVWUzmNoqBWCA6PuN+DvRkvO1XLSkjuS0sEu/lFa4D2zXL4q+IVieRcMVtZJWaDtbR9oRiSFilS+xMkNsbyMYYA6Kli77rX8Z8zUhpj1X/ZvwIH2d89xFum5cMe1m/x4iFJ8xPZRxwqrYTAly+XUBBN0fG3EKn8bDKPHhQUbvzKonWEXb0MVBYvRmCW7Qt1Smfmo3STdaAOPuyByzChywW2KH6zldO/Gdg+ksLMQfFTewcxZqDivGfB9qpIEN98FnkEYs+0c20zcjWbjVVEv5IwWKIgCf5pP0=
  on:
    all_branches: true
