language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: pachkun
  password:
    secure: JcILzUoer2EC2CD2KEWKxHkdiqI/PVz9Ky2CLb9JU56R86RMcN6YCaq5O7ierOVisyCuoC6t8jWZBNh4gs3Y0GMJq7wtMopEA1oE+Y8ZLOZuSS48zJMFpqY8QyxXK2W6OP8ndFJBPYmTqRoPEHDeY/Uz/IbFbh6gNi3Dy3j+HsFRsZeuQPOogENVB8D1wEAUrs9SLNKq0j48Pqo92tEZL0C740Q3hhXru2r++ZGtMlHwVACOjX8tRyInXLAfNzrG0s3BV0au0C+XwS5GekQHiwbLLy7RuRh8fyWgRHq/FxRDrpsnIYp18srmEexhubjpUVAsCeAmWsgyc+F1f6SSlsJRkGfzMpcgJimtV+LbmDY8Me3/349cWsfVeUZHHn8ZaPSVGUPDI91PhuOGc0aEbOhw6xRcm6FgB+DKozjJ5oH0Ck0ISDQ0winOVIpNbOt5nGImRw8tWv7uR8awBjXpaJSWxOhQmCiMwozVQUlLNMtQGZuZETggAfhHfLmlHYsCLVdcT7a2pcPAJkwqZNIKvskSQeB3qJM1QWOQ/7jZUSnH705MyZ/jcrDVM2JpxPNHhFkpKe9jJEpxslReAqL5kEXwA6r5DZIm7QomfSWFfyu///6iY9kzQC2MKgaz4x3O7xlocrLU4omXXNg9AQOJ1eOpooXAieIIg7rnJjUcNXM=
  on:
    tags: true