language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: pachkun
  password:
    secure: XwR35GpLJdJdhPX3Ms0ch2flkUCWiD+MZSDbplrmsm6IR8wR8q6X8EteB8Y9xXnAXtY+oYxwracTmrz5l8KEAL5T7gS3VYeUCjDzwbw7yVMrP4MSPr/72ZuvaJmhVDc5DdS4eYFKEJfYjdhp4mfNdIJva/PxPQyt6CqlAxaN4f3KbkpVFSw+ivuuWouY0py/Yxhtp+Ja+GzGEBl1G/cfd6uW0A2Bp52Km+bX5uAYde5jNFnsjh170cuIzWzglbV6apV8wJlNXApMvNKJeVKzD/w68c9vbhOO8AVJsa7nFboyJmKjfFRVXGUaKEsTi99xAjck9Ovas/wLnpRMVAuW33KTO612xCql7paOdw+VmFBZw4B9Ez8GPIDcTJ3CaMFJYUGiIkSmfIb7wJ/hGbktU1sjIMtM/PL9kPwa8c1xOBBQIgYo86BxctTokMcwCVbAwPN+rF8YMDa1uP06J1mdxfzfeGy6XsHk94zff7I1+4DJiGdUu/B9xw+KgSACJIA2UgC47CgkOJP1LIog5Ilz+NQ4XhS4rRQ75sJyMSLUN1MpY/oXIFM1qm2xn5Gfl/7zNLlWM/ESIO9Tbg4P+A2896TLPTUkp92VLnaxj9DBIjGVTu5gGL/y7LWcC61dY5kY/7G+pvRNvSZRtiXgKyYpJ25YI6glyxQkPXJdLo6AeEQ=
  on:
    all_branches: true
