language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: pachkun
  password:
    secure: KVrEOCaM78rd5uged/5I5uugoe0zllYYKWD9MC2NPYawb/f8YA1s2jYUbDrDzgXDf6767rRkeh60Qy48CHszobGq38qvK2kwjYdGcuCEHHEmcCjZj+W3jhs4taLPCw3oIApyRTkbk3JFBHNc3pbr/1yh5/ag9IEvvsE/K3S3/QcjNHcZx8b3budqkMWv3H8teeTsj1obVjyDfkEpy0W6G2BrxfzFxk+7xkUNXP5V/zF5fg7BKfM9flz6sKDwqNla+WYNmJY7KSMqyMgRRLF8z+1eePS1OyUENNy6lJtg9Gwis6HGMrbDLw+8u3JGrtQLlUdQfeXK0151JWMKO8t6zMQk2AWXShupbU3C00wuGXHsZlPs97E3KxLPCnj6+/gKEdW5H6zUc/byzXX4q9McUeti1bbVZWol6K3Idl3V0jUu+U8KnXzTuBM/uQAxRK4WQTW/Ve+fsIWgNd8at37Km+HkR4tyPdFTn5kZYSWB4y8LIH+jioUNaghjrfCyaAiMzr2FsouMJ6URjA0Acd1JomMvWEBO+tSSkLBuuLP00bdAv1EeXbG93Zut4ohirIjkDSOWa31gG0FMGrtOaxFQM30gKIfOdKMKAsSTtj36KYiplbqOuin6rdV9nvzAH4XOhng8FuV+nlrhNoSsVk8zRzcYMQc+kzPtwU9DjpXDzdw=
  on:
    all_branches: true
