language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: pachkun
  password:
    secure: D7r96AJdZSG9YAbP2Cn/i0qbVSqZ5vASHTacIK7I0a6afUnrwW0pvShAPMu75DVOTR3xg/uFcIPso2+qiu9MeFaL2HQ/g6IoxJaxT7IKGVyluWLRtv4+PfHiwaKzsv1CeyHzsAcK5rkaVgPVKjsg7wAxDvTjs137OKJIa5OhY2KI8VnvlcohmKGXg7DFF/yHn988CVRU6rlC1UOLD7TCzg3u0QfGmbYs3kz40DULC4UJQ5h58vEzLpBLt0DksidQwSxlcQIap5NsYtQTtY+wH2h3V1My//Mv0olmbgwRKALZT8juokzmXHkgMn5/68NiC6SySr/fArX+P+/yVQnMG/Rq5CxUfmJLio94X2xntQ1qrzC+YZd3s5qDpXAPdsn+05Ip9R3DFnlhCvY2j0CNCy1003XQhqpQqGnJro/0bm3CIFxKBdYFpvtpd/7aupGJ3RgefQKRhwJRk+fMsARleYZXj8JkUjNH9SHnrg5nGqQNNLqQFj24m9c17GX97Eye/2DTJK6ZY4+SbS1WjQluRfw8lOGqSMc8ToEYfBlVE6zaS/TXWtdMIbC8/KOkQpV+dT0kgFL6FCpX7CieNWwbpoaB1zqIeLmCGOcLJw2xZotjFm0dSnMP4KSxz5tpRPe9QaY+a0ORe2y/f+Ex4sYgsr0if8iknyG7dgZNlZqU/iE=
  on:
    tags: true
